### ISSUE TITLE
Context apparently died but still running?

### ISSUE THREAD

**Issue by nikoskip** [amphp/parallel#51] opened 2018-05-04 13:53 UTC
Hi,

I'm using `amp` and `parallel` from about 1 year ago with no issues at all. Recently, I have updated both using Composer and now, from time to time, I'm getting this error:

> [2018-05-04 08:30:04] app.CRITICAL: Error sending ID 4833. Error: The channel closed unexpectedly. Did the context die? {"script":"Watcher.php"} []

The weird thing is that according to my log's the thread is still running:

```
[2018-05-04 08:30:04] app.INFO: Processing ID 4833 {"script":"Watcher.php"} []
[2018-05-04 08:30:04] app.CRITICAL: Error sending ID 4833. Error: The channel closed unexpectedly. Did the context die? {"script":"Watcher.php"} []
----- AT THIS POINT THE THREAD SHOULD BE DEAD, BUT I'M GETTING LOGS FROM IT ----
[2018-05-04 08:32:45] app.INFO: Sending batch 0 to 1000 emails ID 4833 {"script":"Watcher.php"} []
[2018-05-04 08:32:50] app.INFO: Batch 0 sent ID 4833 {"script":"Watcher.php"} []
[2018-05-04 08:33:51] app.INFO: Sending batch 1 to 1000 emails ID 4833 {"script":"Watcher.php"} []
[2018-05-04 08:33:56] app.INFO: Batch sent 1 ID 4833 {"script":"Watcher.php"} []
[2018-05-04 08:34:19] app.INFO: Sending batch 2 to 1000 emails ID 4833 {"script":"Watcher.php"} []
[2018-05-04 08:34:26] app.INFO: Batch sent 2 ID 4833 {"script":"Watcher.php"} []
[2018-05-04 08:34:29] app.INFO: Sending batch 3 to 1000 emails ID 4833 {"script":"Watcher.php"} []
[2018-05-04 08:34:38] app.INFO: Batch sent 3 ID 4833 {"script":"Watcher.php"} []
[2018-05-04 08:34:40] app.INFO: Sending batch 4 to 1000 emails ID 4833 {"script":"Watcher.php"} []
[2018-05-04 08:34:48] app.INFO: Batch sent 4 ID 4833 {"script":"Watcher.php"} []
[2018-05-04 08:34:50] app.INFO: Sending batch 5 to 278 emails ID 4833 {"script":"Watcher.php"} []
[2018-05-04 08:34:52] app.INFO: Batch sent 5 ID 4833 {"script":"Watcher.php"} []
[2018-05-04 08:34:52] app.INFO: Invalid emails ID 4833: 0 | Array ( )  {"script":"Watcher.php"} []
[2018-05-04 08:34:52] app.INFO:  Done ID 4833 | Emails sent: 5278 | Final state: sent {"script":"Watcher.php"} []
```

Hope you can help me, thanks!

**Comment by nikoskip** [comment] 2018-05-04 13:58
BTW, after the `Processing ID 4833` part of the log, my script execute a query that can take 2-4 minutes to execute. Maybe that is the problem?

**Comment by kelunik** [comment] 2018-05-04 17:06
@nikoskip Random guess, but are you on macOS?

**Comment by nikoskip** [comment] 2018-05-04 17:46
@kelunik I'm developing under macOS but the live code is running under Fedora .

**Comment by kelunik** [comment] 2018-05-05 07:06
And it happens in both systems or just one of them?

**Comment by nikoskip** [comment] 2018-05-07 01:29
I haven't tested on my local machine yet, but the problem showed up on production (Fedora).

I will test it this week, but I'm using Docker on my local, using the official PHP repo, so the test will not be like running native on macOS.

**Comment by nikoskip** [comment] 2018-05-07 18:09
Hi again,

I made some test on my side, but I'm not able to reproduce the issue. On production is still ocurring one to two times a day, but I can't figure out a pattern.

Do you need more info like a sample code of what I'm doing, software version, etc?

Thanks!

**Comment by kelunik** [comment] 2018-05-07 19:15
Ok, so it's probably not related to the `amphp/byte-stream` issue we fixed recently, because I think that only happened on macOS. Nonetheless, do you have the latest version of `amphp/byte-stream` installed?

If you have a minimal script that's enough to reproduce it on your side, that would definitely be helpful.

**Comment by nikoskip** [comment] 2018-05-09 15:52
According to my `composer.lock` file I'm running `byte-stream v1.3.1` with reference `1b75b122e6f069e7d102eef065dc192119d99ca7`.

**Comment by kelunik** [comment] 2018-05-09 16:52
@nikoskip Could you share additional details regarding the exception? I'm mostly interested in the exception chain, so the messages of the previous exceptions, maybe also the full stack traces.

If it turns out to be failed writes after multiple attempts, you can try changing [this line](https://github.com/amphp/byte-stream/blob/24b2530ec74ea4964a548235806744709cc9a650/lib/ResourceOutputStream.php#L15) to a higher number, e.g. `1024` for a test.

**Comment by nikoskip** [comment] 2018-05-11 13:58
@kelunik here you have a full stack trace of the exception:

```
"class": "Amp\\Parallel\\Sync\\ChannelException",
"message": "The channel closed unexpectedly. Did the context die?",
"code": 0,
"file": "\/home\/app\/mailing\/sender\/vendor\/amphp\/parallel\/lib\/Sync\/ChannelledStream.php:68",
"trace": [
    "{\"function\":\"Amp\\\\Parallel\\\\Sync\\\\{closure}\",\"class\":\"Amp\\\\Parallel\\\\Sync\\\\ChannelledStream\",\"type\":\"->\",\"args\":[]}",
    "\/home\/app\/mailing\/sender\/vendor\/amphp\/amp\/lib\/Coroutine.php:74",
    "\/home\/app\/mailing\/sender\/vendor\/amphp\/amp\/lib\/Internal\/Placeholder.php:127",
    "\/home\/app\/mailing\/sender\/vendor\/amphp\/amp\/lib\/Deferred.php:41",
    "\/home\/app\/mailing\/sender\/vendor\/amphp\/byte-stream\/lib\/ResourceInputStream.php:177",
    "\/home\/app\/mailing\/sender\/vendor\/amphp\/byte-stream\/lib\/ResourceInputStream.php:165",
    "\/home\/app\/mailing\/sender\/vendor\/amphp\/parallel\/lib\/Sync\/ChannelledSocket.php:32",
    "\/home\/app\/mailing\/sender\/vendor\/amphp\/amp\/lib\/Loop\/NativeDriver.php:101",
    "\/home\/app\/mailing\/sender\/vendor\/amphp\/amp\/lib\/Loop\/Driver.php:130",
    "\/home\/app\/mailing\/sender\/vendor\/amphp\/amp\/lib\/Loop\/Driver.php:70",
    "\/home\/app\/mailing\/sender\/vendor\/amphp\/amp\/lib\/Loop.php:76",
    "\/home\/app\/mailing\/sender\/Watcher.php:33"
]
```

I'm going to change `MAX_CONSECUTIVE_EMPTY_WRITES`  to a higher number and see how it behaves.

Thanks!

**Comment by NicklasWallgren** [comment] 2018-05-14 14:16
I have also encountered this issue on an Centos 7 PHP 7.1. I updated this package from v0.1.8 to v0.2.5, I cannot replicate the issue using docker php:7.1-zts on OSX.

```
string(53) "The channel closed unexpectedly. Did the context die?"
string(7184) "#0 [internal function]: Amp\Parallel\Sync\ChannelledStream->Amp\Parallel\Sync\{closure}()
#1 /var/www/fras/dev2/vendor/amphp/amp/lib/Coroutine.php(74): Generator->send(NULL)
#2 /var/www/fras/dev2/vendor/amphp/amp/lib/Internal/Placeholder.php(127): Amp\Coroutine->Amp\{closure}(NULL, NULL)
#3 /var/www/fras/dev2/vendor/amphp/amp/lib/Deferred.php(41): class@anonymous->resolve(NULL)
#4 /var/www/fras/dev2/vendor/amphp/byte-stream/lib/ResourceInputStream.php(92): Amp\Deferred->resolve(NULL)
#5 /var/www/fras/dev2/vendor/amphp/amp/lib/Loop/NativeDriver.php(172): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}('d', Resource id #7, NULL)
#6 /var/www/fras/dev2/vendor/amphp/amp/lib/Loop/NativeDriver.php(68): Amp\Loop\NativeDriver->selectStreams(Array, Array, 4.973)
#7 /var/www/fras/dev2/vendor/amphp/amp/lib/Loop/Driver.php(130): Amp\Loop\NativeDriver->dispatch(true)
#8 /var/www/fras/dev2/vendor/amphp/amp/lib/Loop/Driver.php(70): Amp\Loop\Driver->tick()
#9 /var/www/fras/dev2/vendor/amphp/amp/lib/Loop.php(76): Amp\Loop\Driver->run()
```

**Comment by kelunik** [comment] 2018-05-18 19:14
@NicklasWallgren Same here, please try whether https://github.com/amphp/parallel/issues/51#issuecomment-387804055 helps and report the result back. Maybe instead of modifying the counter, add some error logging [here](https://github.com/amphp/byte-stream/blob/24b2530ec74ea4964a548235806744709cc9a650/lib/ResourceOutputStream.php#L87) to know whether the condition is triggered, regardless whether it shows up in the exception that happens.

**Comment by nikoskip** [comment] 2018-05-18 19:40
@kelunik I changed `MAX_CONSECUTIVE_EMPTY_WRITES` to 1024 and I still happens, less frequent but happens. Before the change I got about 1 ~ 4 errores a day, now I'm only getting one.

One intersting thing is sometimes the PHP process gets stucked consuming 100% of CPU, not always but 50% of the time. I'm running my task using `crontab` and I have to constantly be checking the server because of this.

I've track down the issue, and is *always* happening in a section of my code when I run a SQL that can take up to 5 minutes (sometimes more) to be executed.

**Comment by kelunik** [comment] 2018-05-18 19:58
@nikoskip The child executes the SQL query in a blocking manner? How many jobs does a child usually get in your code?

**Comment by nikoskip** [comment] 2018-05-18 20:34
@kelunik yes, the SQL is synchronous.

I'm running a email marketing campaing service, so I have the main PHP script who spawns threads, each thread is a different campaign. The script runs every 5 minutes, so for instance if at 16:30:00 I have 5 campaign to send, the script will create 5 threads. In production, I can spawn up to 10 different threads.

**Comment by kelunik** [comment] 2018-05-18 23:17
@nikoskip But the work only happens in the children, there's basically one job per worker?

**Comment by NicklasWallgren** [comment] 2018-06-21 09:34
@kelunik Alright, I think I might have found the cause of my issue.

The data read in the [ResourceInputStream](https://github.com/amphp/byte-stream/blob/24b2530ec74ea4964a548235806744709cc9a650/lib/ResourceInputStream.php#L77)   contains the following: 
`syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in /var/www/fras/dev2/vendor/amphp/parallel/lib/Context/Internal/process-runner.php on line 7`

It seems like it spawns a PHP-process using the binary in /usr/bin/php (PHP 5.4), which it didn't in v1.1.8.

We are running PHP-FPM 7.1 using SCL. The default installed version of PHP is 5.4.

**Comment by bwoebi** [comment] 2018-06-27 11:59
Should we read the contents from the stderr stream when getting a channel exception, as typically the reason is to be found on stderr (error message)? And attach that to the exception message

**Comment by bwoebi** [comment] 2018-06-27 12:08
https://github.com/amphp/parallel/blob/master/lib/Context/Process.php#L132-L133

@kelunik What do you think about putting PHP_BINDIR first? php-fpm and php (the cli) usually are installed in the same directory. (and if it is, it's most likely also the correct one).

Additionally, package repositories often contain binaries which are suffixed with a php version, e.g. `php5.6`  and `php-fpm5.6`. We may desire to parse this and try calling the correct version of php then.

**Comment by kelunik** [comment] 2018-06-27 19:38
@bwoebi `PHP_BINDIR` is the path at compilation, which might not be the same path as the current path where PHP is installed. Not sure whether that should be first.

I'd like to keep the can of worms closed and not attempt to figure out binaries named `php5.6`, rather read and respect some environment variable.

**Comment by kelunik** [comment] 2019-05-30 11:32
We made quite some improvements to the `amphp/process` library in the meantime. I believe this issue should be fixed as well, but I'm not 100% sure. If you still encounter this issue with up-to-date versions, please respond, so we can re-open the issue.

**Closed by kelunik** 2019-05-30 11:32 UTC
Labels: bug

**Comment by nikoskip** [comment] 2019-05-30 16:23
I would really like to test this out, but I'm working in a new company right now, so I don't have access to the code 😢
